# need 4 gpus

project: coconut
save_path: outputs/
name: gsm-coconut-qwen

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: Qwen/Qwen2.5-0.5B
load_model_path: outputs/gsm-cot-qwen
seed: 0
resume: 3
bf16: True
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: True
batch_size_training: 16
debug: False
gradient_accumulation_steps: 1
num_epochs: 5
lr: !!float "1e-4"
weight_decay: 0.01
