# need 4 gpus

project: coconut
save_path: outputs/
name: gsm-smol

only_eval: False

coconut: True
cot: False
no_cot: False

c_thought: 2
cot_epochs: 6
epochs_per_stage: 5
max_latent_stage: 3
pad_latent_to_max: True

# replacement_method: "-1"
# replacement_method: "-2"
# replacement_method: "0.5"
replacement_method: "ie+supressed[0.5:]"
# replacement_method: "hs+supressed[0.5:]"
# replacement_method: "supressed[0.5:]"

save_only_improve: True
uniform_prob: 0.0
# Qwen/Qwen2.5-0.5B-Instruct
# Qwen/Qwen2.5-0.5B
# model_id: fdyrd/QwenMath-0.5B
model_id: HuggingFaceTB/SmolLM2-135M-Instruct
# model_id: plaguss/Qwen2.5-0.5B-Math-Shepherd-PRM-0.2
load_model_path: 
seed: 0
resume: 0
bf16: True
bf16_weight: False
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: False
batch_size_training: 32
max_size: 1000000000 # in verl 8k is enougth https://github.com/volcengine/verl/blob/main/examples/ppo_trainer/verl_getting_started.ipynb
debug: False
gradient_accumulation_steps: 4
num_epochs: 26

# this could work but I'd need to work out how to do it over the whole scdule and resume
# lr: !!float "1e-3" 
# lr_scheduler_type: cosine

lr: !!float "1e-4" 
# lr_scheduler_type: constant_with_warmup
# system_prompt: |
#   Solve the math question by multiple short reasoning steps like `<<5*0+1*2=?>>` OR silently within `<|start-latent|><|end-latent|>`. Then return the final answer like `### 2\n<|im_end|><|im_end|>`. No other preamble or comments are allowed.
# weight_decay: 0.01
weight_decay: 0.0
