# need 4 gpus

project: coconut
save_path: outputs/
name: gsm-cot-qwen

only_eval: False

coconut: False
cot: True
no_thoughts: False
no_cot: False

c_thought: 0
epochs_per_stage: 1
max_latent_stage: 0
pad_latent_to_max: True

save_only_improve: True
uniform_prob: 0.0
model_id: Qwen/Qwen2.5-Math-1.5B
# deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
load_model_path: None
seed: 0
resume: 0
bf16: True
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: False
batch_size_training: 4
debug: False
gradient_accumulation_steps: 1
num_epochs: 5
lr: !!float "2e-4"
weight_decay: 0.01
# https://qwen.readthedocs.io/en/latest/training/SFT/llama_factory.html
